import "~/styles/globals.css";
import styles from './layout.module.css'; 
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Parf",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={styles.body}>
        {/* 添加导航栏 */}
        <header className={styles.navbar} style = {{ marginBottom:'5px'}}>
          <nav className={styles.navContainer}>
            {/* 左侧导航链接 */}
            {/* <ul className={styles.navList}>
              <li><a href="#home">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul> */}
            {/* 右侧标题 */}
            <div className={styles.navTitle}>
              <h2>Parf : Adaptive Parameter Refining for Abstract Interpretation</h2>
            </div>
          </nav>
        </header>
        {/* 内容部分 */}
        <div className={styles.content}>
          <TRPCReactProvider>{children}</TRPCReactProvider>
        </div>
      </body>
    </html>
  );
}
